package Login;

import Patient.PatientPageGUI;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.URL;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author harra
 */
public class LoginForm extends javax.swing.JFrame {

    Login login = new Login();

    /**
     * Creates new form TestForm
     */
    public LoginForm() {
        initComponents();
        initCustomComponents();
        setVisible(true);
    }

    private void initCustomComponents() {
        setFrameIcon(this, "/icons/medical-appointment.png");
        scaleImage(imgLabel, "/images/unlock-img.jpg");
    }

    public void setFrameIcon(JFrame frame, String filepath) {
        URL resource = getClass().getResource(filepath);
        ImageIcon icon = new ImageIcon(resource);
        Image image = icon.getImage();
        frame.setIconImage(image);
    }

    public void scaleImage(JLabel imgLabel, String filepath) {
        URL resource = getClass().getResource(filepath);
        ImageIcon icon = new ImageIcon(resource);

        // Scale image to fix jLabel
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(imgLabel.getWidth(), imgLabel.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        imgLabel.setIcon(scaledIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        imgLabel = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        emailTxtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        togglePasswordVisibilityBtn = new javax.swing.JToggleButton();
        loginSubmitBtn = new javax.swing.JButton();
        passwordTxtField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login - AppointWell");
        setResizable(false);

        mainPanel.setLayout(new java.awt.BorderLayout());

        imgLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        mainPanel.add(leftPanel, java.awt.BorderLayout.LINE_START);

        rightPanel.setBackground(new java.awt.Color(196, 30, 58));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 35)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Welcome To AppointWell !");
        jPanel1.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Login to continue");
        jPanel2.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(153, 51, 0));
        jPanel3.setOpaque(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Email Address");

        emailTxtField.setBackground(new java.awt.Color(196, 30, 58));
        emailTxtField.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        emailTxtField.setForeground(new java.awt.Color(255, 255, 255));
        emailTxtField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        emailTxtField.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/email-icon.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Password");

        togglePasswordVisibilityBtn.setBackground(new java.awt.Color(196, 30, 58));
        togglePasswordVisibilityBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hide-icon.png"))); // NOI18N
        togglePasswordVisibilityBtn.setBorder(null);
        togglePasswordVisibilityBtn.setContentAreaFilled(false);
        togglePasswordVisibilityBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        togglePasswordVisibilityBtn.setFocusPainted(false);
        togglePasswordVisibilityBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/show-icon.png"))); // NOI18N
        togglePasswordVisibilityBtn.setRolloverEnabled(false);
        togglePasswordVisibilityBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                togglePasswordVisibilityBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                togglePasswordVisibilityBtnMouseReleased(evt);
            }
        });

        loginSubmitBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loginSubmitBtn.setForeground(new java.awt.Color(196, 30, 58));
        loginSubmitBtn.setText("LOGIN");
        loginSubmitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginSubmitBtn.setEnabled(false);
        loginSubmitBtn.setFocusPainted(false);
        loginSubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginSubmitBtnActionPerformed(evt);
            }
        });

        passwordTxtField.setBackground(new java.awt.Color(196, 30, 58));
        passwordTxtField.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        passwordTxtField.setForeground(new java.awt.Color(255, 255, 255));
        passwordTxtField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        passwordTxtField.setCaretColor(new java.awt.Color(255, 255, 255));
        passwordTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordTxtFieldKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(loginSubmitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(emailTxtField))
                    .addComponent(passwordTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(togglePasswordVisibilityBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(togglePasswordVisibilityBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(passwordTxtField))
                .addGap(66, 66, 66)
                .addComponent(loginSubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(rightPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void togglePasswordVisibilityBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_togglePasswordVisibilityBtnMousePressed
        passwordTxtField.setEchoChar((char) 0);
    }//GEN-LAST:event_togglePasswordVisibilityBtnMousePressed

    private void togglePasswordVisibilityBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_togglePasswordVisibilityBtnMouseReleased
        passwordTxtField.setEchoChar('*');
    }//GEN-LAST:event_togglePasswordVisibilityBtnMouseReleased

    private void loginSubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginSubmitBtnActionPerformed

        String email = getUserEmail();
        char[] password = retrievePassword();

        try {
            if (login.isPatientLogin(email, password)) {
                this.dispose();
            } else try {
                if (login.isAdminLogin(email, password)) {
                    this.dispose();
                } else if (login.isDoctorLogin(email, password)) {
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Email or Password is invalid", "Login Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (IOException | ParseException ex) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loginSubmitBtnActionPerformed

    private void passwordTxtFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordTxtFieldKeyPressed

        String email = getUserEmail();

        if (email.trim().length() != 0) {
            loginSubmitBtn.setEnabled(true);
        }
    }//GEN-LAST:event_passwordTxtFieldKeyPressed

    private String getUserEmail() {
        return emailTxtField.getText();
    }

    private char[] retrievePassword() {
        return passwordTxtField.getPassword();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        LoginForm login = new LoginForm();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailTxtField;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JButton loginSubmitBtn;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPasswordField passwordTxtField;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JToggleButton togglePasswordVisibilityBtn;
    // End of variables declaration//GEN-END:variables
}
